### ISSUE TITLE
Password not working

### ISSUE THREAD

**Issue by JustGlowing** [MMU-TDMLab/CompLex#1]
I jus registered to the task and received the password, but it doesn't allow me to decompress the train data.

**Comment by mattshardlow** [comment]
Hi, make sure you're using 7z. I just tried it on my machine (Mac running macOS 10.15) and it didn't work when the file browser prompted for the password, but it did work using 7z via command line. Not sure what the file browser was doing, but I assume it was using some other protocol and failing.

**Comment by JustGlowing** [comment]
Thank you, using 7z via the command line solve the issue.
