### ISSUE TITLE
What's the password for train.7z?

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [MMU-TDMLab/CompLex#10]
The readme says

> You will need the password to decompress the 7zip archive, which can be obtained by registering for the shared task.

however the [registering form](https://forms.gle/5TYt195W8PGPY5hJ9) for the shared task is closed.

**Comment by mattshardlow** [comment]
Hi, thanks for your interest in the data. I've now released the full data without password protection following the release of  the shared task results. Please remember to cite the paper in the readme in any publications using the data.

**Comment by Franck-Dernoncourt** [comment]
Thanks!
