### ISSUE TITLE
Regarding Page Limit for paper submission

### ISSUE THREAD

**Issue by raksha-lab** [MMU-TDMLab/CompLex#11]
Kindly extend the page limit to 6 or 8 pages for teams participating in both the subtasks.

**Comment by mattshardlow** [comment]
This limit is imposed by SemEval, not by us. The page limit is 4 pages plus extra for references. The GitHub area is the appropriate place to ask questions regarding the dataset, not about the submission format for the shared task. Please use the following email address for Shared Task Queries: semeval-2021-task-1-organizers@googlegroups.com

**Comment by raksha-lab** [comment]
Thank you for response.
regards
