### ISSUE TITLE
the word frequency reported in the baseline model refers to the target word only frequency?

### ISSUE THREAD

**Issue by lis-kp** [MMU-TDMLab/CompLex#3]
hi, I wonder if the word frequency reported in the linear regression baseline model refers to the target word only frequency. 
thanks.

**Comment by mattshardlow** [comment]
Yes, the frequency is that of the target word. For MWEs, the average frequency of the tokens was taken. It is worth noting that the baseline model was trained on a previous version of CompLex so the results will differ for the released version (there are more annotations per instance in the released version). I will release some baseline stats for the current released version in the next few weeks.

**Comment by lis-kp** [comment]
ok, thank you very much.
