### ISSUE TITLE
Error when submitting on Codalab

### ISSUE THREAD

**Issue by JustGlowing** [MMU-TDMLab/CompLex#8]
Hi there,

I'm trying to make a submission on Codalab using the starting kit available at https://competitions.codalab.org/competitions/27420#participate-get_starting_kit

Unfortunately I always get this error:

`Invalid file type (text/csv).`

Any hint on how to solve this?

**Comment by mattshardlow** [comment]
Hi Giuseppe,

Please follow the submission instructions at: https://competitions.codalab.org/competitions/27420#learn_the_details-format

Specifically, you need to zip your file prior to submission.

Best,

Matt

**Comment by JustGlowing** [comment]
I missed that bit, thank you!

**Comment by azizcu** [comment]
Failed submission or submission error are count for max 3 submission for
evaluation phase?

**Comment by mattshardlow** [comment]
Hi, These shouldn't count, but please could you email this query to the following address: semeval-2021-task-1-organizers@googlegroups.com. Commenting on a closed issue isn't the best way to reach us.
